"""
Student C: Bitstream Decoder (解压译码器)
============================================
Core tasks:
  1. Read the binary compressed file generated by Student B
  2. Parse the file header to extract the codebook (dictionary / tree)
  3. Rebuild the Huffman tree for decoding
  4. Read the compressed bitstream and walk the tree bit-by-bit
  5. Reconstruct the original text (D') — must be identical to D (lossless)
  6. Write the reconstructed text for Student D's verification

Algorithm Overview
------------------
Decoding uses the Huffman tree directly:
  - Start at the root node.
  - For each bit read from the compressed data:
      '0' → go left,  '1' → go right
  - When a leaf node is reached:
      output the character stored at the leaf,
      reset to the root node,
      continue reading bits.
  - Stop when all meaningful data bits have been consumed (account for padding).

The prefix-free property of Huffman codes guarantees unambiguous decoding:
no valid code is a prefix of any other code, so we always know exactly
when one code ends and the next begins.
"""

import struct
from typing import BinaryIO, Dict, Optional, Tuple

# Import HuffmanNode from Student A's module (used to rebuild the tree)
from .tree import HuffmanNode


# ======================================================================
# 1.  Bit-by-bit reader for the compressed data section
# ======================================================================

class BitReader:
    """Reads individual bits from a byte stream, MSB-first.

    This is the inverse of Student B's BitWriter.  Bits are consumed from
    the MSB (most significant bit) of each byte downward.

    Usage
    -----
    >>> br = BitReader(data_bytes, padding_bits=3)
    >>> bit = br.read_bit()   # returns 0 or 1, or None if exhausted
    """

    def __init__(self, data: bytes, padding_bits: int = 0):
        """
        Parameters
        ----------
        data : bytes
            The packed byte sequence containing the compressed bitstream.
        padding_bits : int
            Number of padding (unused) bits in the last byte (0-7).
            These are the LEAST-significant bits of the last byte.
        """
        self._data = data
        self._byte_index = 0
        self._bit_index = 0       # 0 = MSB, ..., 7 = LSB
        self._total_bits = len(data) * 8 - padding_bits
        self._bits_read = 0

    def bits_remaining(self) -> int:
        """Return the number of meaningful bits still unread."""
        return self._total_bits - self._bits_read

    def read_bit(self) -> Optional[int]:
        """Read the next bit.

        Returns
        -------
        int (0 or 1) if a bit is available, None if the stream is exhausted.
        """
        if self._bits_read >= self._total_bits:
            return None

        byte = self._data[self._byte_index]
        # Extract the current MSB-side bit
        bit = (byte >> (7 - self._bit_index)) & 1

        self._bit_index += 1
        self._bits_read += 1

        if self._bit_index == 8:
            self._bit_index = 0
            self._byte_index += 1

        return bit

    def read_bits(self, n: int) -> str:
        """Read n bits and return as a string of '0'/'1'.

        If fewer than n bits remain, returns the available bits.
        """
        result = []
        for _ in range(n):
            b = self.read_bit()
            if b is None:
                break
            result.append(str(b))
        return "".join(result)


# ======================================================================
# 2.  Header parsing — extract the codebook from the compressed file
# ======================================================================

def _read_exact(f: BinaryIO, n: int) -> bytes:
    """Read exactly n bytes from a binary file, raising on short read."""
    data = f.read(n)
    if len(data) < n:
        raise EOFError(
            f"Unexpected end of file: expected {n} bytes, got {len(data)}"
        )
    return data


def parse_codebook(f: BinaryIO) -> Dict[str, str]:
    """Parse the codebook section from a compressed Huffman file.

    The file position must be at the start of the codebook section
    (immediately after the 7-byte header: magic + padding + entry count).

    Parameters
    ----------
    f : BinaryIO
        A binary file object opened in 'rb' mode, positioned at the
        start of the codebook.

    Returns
    -------
    dict
        Mapping from character (str) to Huffman code (str of '0'/'1').
    """
    # Read number of codebook entries (uint16, big-endian)
    raw = _read_exact(f, 2)
    num_entries = struct.unpack("!H", raw)[0]

    codebook: Dict[str, str] = {}

    for _ in range(num_entries):
        # --- Read 4-byte Unicode code point (uint32, big-endian) ---
        raw = _read_exact(f, 4)
        code_point = struct.unpack("!I", raw)[0]
        char = chr(code_point)

        # --- Read 1-byte code length L ---
        raw = _read_exact(f, 1)
        bit_len = raw[0]

        # --- Read ceil(L/8) bytes containing the code bits ---
        num_bytes = (bit_len + 7) // 8
        raw = _read_exact(f, num_bytes)

        # Extract the left-aligned bits
        code_int = int.from_bytes(raw, "big")
        # Right-shift to remove the zero-padding on the right
        shift = num_bytes * 8 - bit_len
        code_int >>= shift

        # Convert to binary string (zero-padded to bit_len)
        code_str = format(code_int, f"0{bit_len}b")
        codebook[char] = code_str

    return codebook


# ======================================================================
# 3.  Rebuild Huffman tree from the codebook
# ======================================================================

def rebuild_tree(codebook: Dict[str, str]) -> HuffmanNode:
    """Rebuild a Huffman tree from a codebook.

    Iterates over each (character, code) pair and walks/constructs
    the tree path: '0' → left child, '1' → right child.  Creates
    internal nodes as needed.  Sets the leaf node's character.

    Parameters
    ----------
    codebook : dict
        char → binary code string (e.g. {'e': '01', 'z': '11010'})

    Returns
    -------
    HuffmanNode
        The root of the reconstructed Huffman tree.
    """
    root = HuffmanNode(char=None, freq=0)

    for char, code in codebook.items():
        node = root
        for bit in code:
            if bit == '0':
                if node.left is None:
                    node.left = HuffmanNode(char=None, freq=0)
                node = node.left
            else:  # bit == '1'
                if node.right is None:
                    node.right = HuffmanNode(char=None, freq=0)
                node = node.right
        # Now at the leaf — assign the character
        node.char = char

    return root


# ======================================================================
# 4.  Decode the bitstream using the tree
# ======================================================================

def decode_bitstream(bit_reader: BitReader, tree_root: HuffmanNode) -> str:
    """Decode a Huffman-encoded bitstream into the original text.

    Walks the Huffman tree from the root node.  Each bit directs:
      '0' → left child
      '1' → right child
    When a leaf node is reached, the character is emitted and the walk
    resets to the root.  This repeats until all bits are consumed.

    Parameters
    ----------
    bit_reader : BitReader
        The bit reader positioned at the start of the compressed data.
    tree_root : HuffmanNode
        The root node of the Huffman tree.

    Returns
    -------
    str
        The fully reconstructed original text (D').
    """
    chars: list = []
    node = tree_root

    # Handle the edge case: if the tree root itself is a leaf
    # (only one unique character in the original text)
    if tree_root.is_leaf():
        while bit_reader.bits_remaining() > 0:
            bit_reader.read_bit()
            chars.append(tree_root.char)
        return "".join(chars)

    while True:
        bit = bit_reader.read_bit()
        if bit is None:
            break  # end of bitstream

        if bit == 0:
            node = node.left
        else:
            node = node.right

        if node is None:
            raise ValueError(
                "Corrupted bitstream: reached a null node. "
                "The compressed data may be damaged."
            )

        if node.is_leaf():
            chars.append(node.char)
            node = tree_root  # reset to root for next code

    # Safety check: we should be at the root when the stream ends
    if node is not tree_root:
        raise ValueError(
            "Corrupted bitstream: ended mid-code. "
            f"Remaining partial path from root: {_node_path(node)}"
        )

    return "".join(chars)


def _node_path(node: HuffmanNode) -> str:
    """Debug helper: describe what we know about a partial path."""
    if node.is_leaf():
        return f"leaf(char={node.char!r})"
    return "internal node"


# ======================================================================
# 5.  Top-level decompress function
# ======================================================================

def decompress(filepath: str) -> str:
    """Decompress a .huff file back to the original text.

    This is the main entry point for Student C's module.  It:
      1. Opens the binary compressed file
      2. Reads and verifies the magic header
      3. Extracts the padding-bits count
      4. Parses the codebook and rebuilds the Huffman tree
      5. Reads the remaining data as a compressed bitstream
      6. Decodes the bitstream character by character
      7. Returns the fully reconstructed text (D')

    Parameters
    ----------
    filepath : str
        Path to the compressed file produced by Student B's encoder
        (e.g. 'output.huff').

    Returns
    -------
    str
        The reconstructed original text D'.  Must be identical to the
        original D for lossless verification.

    Raises
    ------
    ValueError
        If the file is not a valid Huffman-compressed file.
    EOFError
        If the file is truncated or corrupted.
    """
    with open(filepath, "rb") as f:
        # --- Step 1: Read and verify magic number ---
        magic = _read_exact(f, 4)
        if magic != b"HUFF":
            raise ValueError(
                f"Not a valid Huffman-compressed file. "
                f"Expected magic b'HUFF', got {magic!r}"
            )

        # --- Step 2: Read padding-bits count ---
        raw = _read_exact(f, 1)
        padding_bits = raw[0]
        if padding_bits > 7:
            raise ValueError(f"Invalid padding value: {padding_bits}")

        # --- Step 3: Parse codebook ---
        codebook = parse_codebook(f)

        if not codebook:
            raise ValueError("Empty codebook: nothing to decode.")

        # --- Step 4: Rebuild Huffman tree ---
        tree_root = rebuild_tree(codebook)

        # --- Step 5: Read the compressed bitstream ---
        # Everything remaining in the file is the compressed data.
        data_bytes = f.read()

    if not data_bytes:
        # Empty data section → original text was empty
        return ""

    # --- Step 6: Decode ---
    bit_reader = BitReader(data_bytes, padding_bits=padding_bits)
    reconstructed_text = decode_bitstream(bit_reader, tree_root)

    return reconstructed_text


def save_decompressed(input_path: str, output_path: str) -> str:
    """Decompress a .huff file and save the result to a text file.

    Parameters
    ----------
    input_path : str
        Path to the compressed .huff file.
    output_path : str
        Path where the reconstructed text will be written.

    Returns
    -------
    str
        The reconstructed text (also written to output_path).
    """
    text = decompress(input_path)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(text)
    return text
